version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evoting
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/evoting
      JWT_SECRET: change_me
      CORS_ORIGINS: http://localhost:3000,https://your-vercel-domain
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  pgdata:
